# External.

Style/TrailingBodyOnMethodDefinition:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Lint/Void:
  Enabled: false

# Internal:

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Lint/MissingSuper:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false
