# External.

Style/TrailingBodyOnMethodDefinition:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Lint/Void:
  Enabled: false

# Internal:

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 25

Lint/MissingSuper:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10
