# frozen_string_literal: true

source 'https://rubygems.org'

gem 'falcon'
gem 'low_type', path: '../../'
gem 'puma'
gem 'rackup'
gem 'sinatra'
gem 'webrick'

group :development do
  gem 'pry'
  gem 'pry-nav'
end
